// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFjoGi7LDEMWyGwWQOJzkJZ-Hg_f_V7G0',
    appId: '1:650880229074:web:99f4a5a6ef2427ea4d970b',
    messagingSenderId: '650880229074',
    projectId: 'dowith-7ff4b',
    authDomain: 'dowith-7ff4b.firebaseapp.com',
    storageBucket: 'dowith-7ff4b.appspot.com',
    measurementId: 'G-J94TJBQJVZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMhb6blwQof1hKT-pn4CRyUfA5LU8iFLM',
    appId: '1:650880229074:android:eb291de177523de64d970b',
    messagingSenderId: '650880229074',
    projectId: 'dowith-7ff4b',
    storageBucket: 'dowith-7ff4b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHk3VKlrNXkGzmiI9UQen-MMci_l63cCI',
    appId: '1:650880229074:ios:983f3624fe64510a4d970b',
    messagingSenderId: '650880229074',
    projectId: 'dowith-7ff4b',
    storageBucket: 'dowith-7ff4b.appspot.com',
    androidClientId: '650880229074-i3tr392u9vga3i4soodnsigcpp8o06in.apps.googleusercontent.com',
    iosClientId: '650880229074-gul30fr78pf1ipobvalbcpv6f6ohti39.apps.googleusercontent.com',
    iosBundleId: 'com.dowithdev.dowith',
  );
}
